// flow-typed signature: df911630b9fc925fef79a20589a522c5
// flow-typed version: <<STUB>>/dva_v1.3.0-beta2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dva'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dva' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dva/dist/dva-min' {
  declare module.exports: any;
}

declare module 'dva/dist/dva' {
  declare module.exports: any;
}

declare module 'dva/dist/fetch-min' {
  declare module.exports: any;
}

declare module 'dva/dist/fetch' {
  declare module.exports: any;
}

declare module 'dva/dist/mobile-min' {
  declare module.exports: any;
}

declare module 'dva/dist/mobile' {
  declare module.exports: any;
}

declare module 'dva/dist/router-min' {
  declare module.exports: any;
}

declare module 'dva/dist/router' {
  declare module.exports: any;
}

declare module 'dva/fetch' {
  declare module.exports: any;
}

declare module 'dva/lib/createDva' {
  declare module.exports: any;
}

declare module 'dva/lib/handleActions' {
  declare module.exports: any;
}

declare module 'dva/lib/index' {
  declare module.exports: any;
}

declare module 'dva/lib/mobile' {
  declare module.exports: any;
}

declare module 'dva/lib/plugin' {
  declare module.exports: any;
}

declare module 'dva/mobile' {
  declare module.exports: any;
}

declare module 'dva/router' {
  declare module.exports: any;
}

declare module 'dva/saga' {
  declare module.exports: any;
}

declare module 'dva/src/createDva' {
  declare module.exports: any;
}

declare module 'dva/src/handleActions' {
  declare module.exports: any;
}

declare module 'dva/src/index' {
  declare module.exports: any;
}

declare module 'dva/src/mobile' {
  declare module.exports: any;
}

declare module 'dva/src/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dva/dist/dva-min.js' {
  declare module.exports: $Exports<'dva/dist/dva-min'>;
}
declare module 'dva/dist/dva.js' {
  declare module.exports: $Exports<'dva/dist/dva'>;
}
declare module 'dva/dist/fetch-min.js' {
  declare module.exports: $Exports<'dva/dist/fetch-min'>;
}
declare module 'dva/dist/fetch.js' {
  declare module.exports: $Exports<'dva/dist/fetch'>;
}
declare module 'dva/dist/mobile-min.js' {
  declare module.exports: $Exports<'dva/dist/mobile-min'>;
}
declare module 'dva/dist/mobile.js' {
  declare module.exports: $Exports<'dva/dist/mobile'>;
}
declare module 'dva/dist/router-min.js' {
  declare module.exports: $Exports<'dva/dist/router-min'>;
}
declare module 'dva/dist/router.js' {
  declare module.exports: $Exports<'dva/dist/router'>;
}
declare module 'dva/fetch.js' {
  declare module.exports: $Exports<'dva/fetch'>;
}
declare module 'dva/index' {
  declare module.exports: $Exports<'dva'>;
}
declare module 'dva/index.js' {
  declare module.exports: $Exports<'dva'>;
}
declare module 'dva/lib/createDva.js' {
  declare module.exports: $Exports<'dva/lib/createDva'>;
}
declare module 'dva/lib/handleActions.js' {
  declare module.exports: $Exports<'dva/lib/handleActions'>;
}
declare module 'dva/lib/index.js' {
  declare module.exports: $Exports<'dva/lib/index'>;
}
declare module 'dva/lib/mobile.js' {
  declare module.exports: $Exports<'dva/lib/mobile'>;
}
declare module 'dva/lib/plugin.js' {
  declare module.exports: $Exports<'dva/lib/plugin'>;
}
declare module 'dva/mobile.js' {
  declare module.exports: $Exports<'dva/mobile'>;
}
declare module 'dva/router.js' {
  declare module.exports: $Exports<'dva/router'>;
}
declare module 'dva/saga.js' {
  declare module.exports: $Exports<'dva/saga'>;
}
declare module 'dva/src/createDva.js' {
  declare module.exports: $Exports<'dva/src/createDva'>;
}
declare module 'dva/src/handleActions.js' {
  declare module.exports: $Exports<'dva/src/handleActions'>;
}
declare module 'dva/src/index.js' {
  declare module.exports: $Exports<'dva/src/index'>;
}
declare module 'dva/src/mobile.js' {
  declare module.exports: $Exports<'dva/src/mobile'>;
}
declare module 'dva/src/plugin.js' {
  declare module.exports: $Exports<'dva/src/plugin'>;
}
